### ISSUE TITLE
(Feature) Rename of ICO Wizard to Token Wizard

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/token-wizard#531]
Problem:
ICO word can cause a legal problem for the project. One of our contributors recommended renaming `ICO Wizard` to `Token Wizard`

Solution:
Rename it.

Let's create a checklist in comments what do we need to modify for renaming

**Comment by Vcoin6** [comment]
Will name change affect marketing.

**Comment by vbaranov** [comment]
**Rebranding checklist**:

- [ ] https://poa.network wizard page (https://poa.network/wizard)
- [ ] Youtube videos titles (https://www.youtube.com/watch?v=Hvs1gICcXGU etc.)
- [ ] Medium paper (https://medium.com/oracles-network/ico-wizard-launch-your-crowdsale-campaign-in-under-10-minutes-47df74c957ba)
- [ ] repo rename https://github.com/poanetwork/ico-wizard
- [ ] footer, header, loader logs
- [ ] Wiki pages (almost all) (https://github.com/poanetwork/ico-wizard/wiki)
- [ ] Rename gitter (https://gitter.im/poanetwork/ico-wizard - chat name and description)
- [ ] Repo README (https://github.com/poanetwork/ico-wizard/blob/master/README.md)
- [ ] Template for issues creation (https://github.com/poanetwork/ico-wizard/blob/master/.github/ISSUE_TEMPLATE.md)
- [ ] Header for solidity source files  (https://github.com/poanetwork/ico-wizard/blob/master/scripts/compileContract.js)
- [ ] Titles for pages: index, invest, crowdsale, manage (https://github.com/poanetwork/ico-wizard/blob/master/src/utils/alerts.js)
- [ ] mention in alerts
- [ ] package.json description of submodules
- [ ] welcome page (https://github.com/poanetwork/ico-wizard/blob/master/src/components/Home/index.js)

**Comment by vbaranov** [comment]
@igorbarinov all changes in current github repo are made from checklist above. Will we rename the repo to `token-wizard` also?

**Comment by igorbarinov** [comment]
yes, will rename the repo too

**Comment by vbaranov** [comment]
@igorbarinov I finished renaming everything, where I have access. I'm passing the baton to you.

**Comment by fvictorio** [comment]
@vbaranov Can we close this? Or those unchecked items are still pending?
